<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Coupling" Id="{80ddf6b9-44b4-4562-b94b-ac30f080db20}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Coupling

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Coupling">
      <LineId Id="45" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>